# Generated by Django 3.2.6 on 2021-08-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0005_auto_20210823_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sequence',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
