# Generated by Django 3.2.6 on 2021-08-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0006_book_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='suffix',
        ),
    ]
