# Generated by Django 3.2.6 on 2021-08-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0008_auto_20210825_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn_10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn_13',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='asin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
