# Generated by Django 3.2.6 on 2021-09-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0012_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dystopia.author'),
        ),
    ]
