# Generated by Django 3.2.6 on 2021-09-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0013_series_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
