# Generated by Django 3.2.6 on 2021-09-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0014_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Novella', 'Novella'), ('Short Story', 'Short Story'), ('Short Story Collection', 'Short Story Collection')], default='Novel', max_length=255, null=True),
        ),
    ]
