# Generated by Django 3.2.6 on 2021-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0015_book_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
