# Generated by Django 3.2.6 on 2021-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0016_series_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='asin',
            field=models.CharField(blank=True, help_text='Amazon Standard Identification Number', max_length=10, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='series',
            name='notes',
            field=models.TextField(blank=True, help_text='For internal use only', null=True),
        ),
    ]
