# Generated by Django 3.2.6 on 2021-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0017_auto_20210904_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='notes',
            field=models.TextField(blank=True, help_text='These notes are for internal use only. Use to explain any problems with the book series.', null=True),
        ),
    ]
