# Generated by Django 3.2.6 on 2021-09-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0018_alter_series_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sequence',
        ),
        migrations.AddField(
            model_name='book',
            name='chronological_sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
