# Generated by Django 3.2.6 on 2021-09-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0020_auto_20210904_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
