# Generated by Django 3.2.6 on 2021-09-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0021_book_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
