# Generated by Django 3.2.6 on 2021-09-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0026_auto_20210906_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
