# Generated by Django 3.2.6 on 2021-09-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0027_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text="Use publisher's webpage for author.", null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='website',
            field=models.URLField(blank=True, help_text="Use publisher's webpage for series.", null=True),
        ),
    ]
