# Generated by Django 3.2.6 on 2021-09-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0028_auto_20210906_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text='The publisher should have a webpage for author with a picture and biography.', null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='website',
            field=models.URLField(blank=True, help_text='The publisher should have a webpage for the series.', null=True),
        ),
    ]
