# Generated by Django 3.2.6 on 2021-09-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0029_auto_20210906_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='wikipedia',
            field=models.URLField(blank=True, null=True, verbose_name='Wikipedia Page'),
        ),
        migrations.AlterField(
            model_name='series',
            name='website',
            field=models.URLField(blank=True, help_text='The publisher should have a webpage for the series.', null=True, verbose_name="Publisher's Website"),
        ),
    ]
