# Generated by Django 3.2.6 on 2021-09-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0030_auto_20210906_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wikipedia',
            field=models.URLField(blank=True, null=True, verbose_name='Wikipedia Page'),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name="Publisher's Website"),
        ),
        migrations.AlterField(
            model_name='series',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name="Publisher's Website"),
        ),
    ]
