# Generated by Django 3.2.6 on 2021-09-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0034_book_publication_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chronological_sequence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
