# Generated by Django 3.2.6 on 2021-09-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0035_alter_book_chronological_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wikipedia',
            field=models.URLField(blank=True, null=True, verbose_name='Wikipedia Page'),
        ),
    ]
