# Generated by Django 3.2.6 on 2021-09-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0036_book_wikipedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_names', 'first_names'], 'verbose_name_plural': 'Authors'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='first_names',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='last_names',
        ),
    ]
