# Generated by Django 3.2.6 on 2021-09-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0037_auto_20210908_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
