# Generated by Django 3.2.6 on 2021-09-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0038_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
    ]
