# Generated by Django 3.2.6 on 2021-09-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0040_auto_20210908_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='amazon_page',
            field=models.URLField(blank=True, null=True, verbose_name='Amazon Page'),
        ),
    ]
