# Generated by Django 3.2.6 on 2021-09-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0042_auto_20210910_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='chronological_order',
            new_name='reading_order',
        ),
    ]
