# Generated by Django 3.2.6 on 2021-09-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0044_auto_20210912_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='goodreads_page',
            field=models.URLField(blank=True, null=True, verbose_name="Goodreads' Page"),
        ),
    ]
