# Generated by Django 3.2.6 on 2021-09-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0045_series_goodreads_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='wikipedia',
        ),
    ]
