# Generated by Django 3.2.6 on 2021-09-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0046_remove_book_wikipedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_short_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
