# Generated by Django 3.2.6 on 2021-09-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0047_book_amazon_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_short_link',
            field=models.URLField(blank=True, null=True, verbose_name='Amazon Short Link'),
        ),
    ]
