# Generated by Django 3.2.6 on 2021-09-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0048_alter_book_amazon_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='asin',
        ),
    ]
