# Generated by Django 3.2.6 on 2021-09-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0049_remove_book_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_short_link',
            field=models.URLField(blank=True, max_length=30, null=True, verbose_name='Amazon Short Link'),
        ),
    ]
