# Generated by Django 3.2.6 on 2021-09-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0051_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
