# Generated by Django 3.2.6 on 2021-09-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0052_auto_20210925_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
