# Generated by Django 3.2.6 on 2021-09-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0055_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
