# Generated by Django 3.2.6 on 2021-09-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0056_alter_series_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprint',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
