# Generated by Django 3.2.6 on 2021-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0057_auto_20210925_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
