# Generated by Django 3.2.6 on 2021-09-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0058_series_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='hidden',
        ),
    ]
