# Generated by Django 3.2.6 on 2021-09-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0059_remove_series_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
