# Generated by Django 3.2.6 on 2021-09-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0061_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
