# Generated by Django 3.2.6 on 2021-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0063_auto_20210928_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_names',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_names',
            field=models.CharField(default='', max_length=255),
        ),
    ]
