# Generated by Django 3.2.6 on 2021-09-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0064_auto_20210928_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_names',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_names',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
