# Generated by Django 3.2.6 on 2021-10-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0065_auto_20210928_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default=211, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='dystopia.author'),
        ),
    ]
