# Generated by Django 3.2.6 on 2021-10-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0067_auto_20211004_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
