# Generated by Django 3.2.6 on 2021-10-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0068_auto_20211004_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='dystopia.author'),
        ),
        migrations.DeleteModel(
            name='Imprint',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
