# Generated by Django 3.2.6 on 2021-10-06 19:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0069_auto_20211006_1455'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
