# Generated by Django 3.2.6 on 2021-10-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0070_alter_author_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
    ]
