# Generated by Django 3.2.6 on 2021-10-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0071_alter_author_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_short_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Amazon Short Link'),
        ),
    ]
