# Generated by Django 3.2.6 on 2021-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0072_alter_book_amazon_short_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_names', 'last_names'], 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_large_image_anchor',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Amazon Large Image Link'),
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_small_image_anchor',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Amazon Small Image Link'),
        ),
    ]
