# Generated by Django 3.2.6 on 2021-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0075_rename_amazon_large_image_link_book_amazon_large_image_anchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_large_image_anchor',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Amazon Large Image Anchor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amazon_small_image_anchor',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Amazon Small Image Anchor'),
        ),
    ]
