# Generated by Django 3.2.6 on 2021-10-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0076_auto_20211016_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='amazon_large_image_anchor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='amazon_small_image_anchor',
        ),
    ]
