# Generated by Django 3.2.6 on 2021-10-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0079_auto_20211016_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subtitle',
        ),
    ]
