# Generated by Django 3.2.8 on 2021-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0083_alter_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='amazon_page',
            field=models.URLField(blank=True, null=True, verbose_name='Amazon Page'),
        ),
        migrations.AddField(
            model_name='author',
            name='goodreads_page',
            field=models.URLField(blank=True, null=True, verbose_name="Goodreads' Page"),
        ),
    ]
