# Generated by Django 3.2.8 on 2021-11-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0085_alter_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.CharField(blank=True, choices=[('Comic', 'Comic'), ('Manga', 'Manga'), ('Novel', 'Novel'), ('Novella', 'Novella'), ('Short Story', 'Short Story'), ('Short Story Collection', 'Short Story Collection')], default='Novel', max_length=255, null=True),
        ),
    ]
