# Generated by Django 3.2.8 on 2021-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dystopia', '0087_alter_book_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
